# Generated by Django 2.2 on 2022-01-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='staus',
            new_name='status',
        ),
    ]
