# Generated by Django 2.2 on 2022-02-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['data_nascimento']},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente_sistema',
        ),
    ]
